import type { ProductConfig } from "@/lib/product/types"
import { presenceLandingCopy } from "@/lib/constants/presence-landing-content"

export const presenceStudioProduct: ProductConfig = {
  id: "presence-studio",
  name: "Presence Studio",
  siteUrl: "https://artificialinfluence.tech",
  logo: "/presence_studio_logo.png",
  logoSizePx: 36,
  logoClassName: "relative z-10",
  favicon: "/presence-studio/favicon.ico",
  appleTouchIcon: "/presence-studio/apple-touch-icon.png",
  webManifest: "/presence-studio/site.webmanifest",
  themeClass: "theme-presence",
  metadata: {
    title: presenceLandingCopy.metadata.title,
    titleTemplate: "%s | Presence Studio",
    description: presenceLandingCopy.metadata.description,
  },
  landing: {
    heroTitle: presenceLandingCopy.hero.title,
    heroDescription: presenceLandingCopy.hero.description,
    primaryCtaLabel: presenceLandingCopy.hero.primaryCtaLabel,
    primaryCtaHref: presenceLandingCopy.hero.primaryCtaHref,
    secondaryCtaLabel: presenceLandingCopy.hero.secondaryCtaLabel,
    secondaryCtaHref: presenceLandingCopy.hero.secondaryCtaHref,
    previewAlt: presenceLandingCopy.hero.previewAlt,
  },
  visibleRoutes: [
    "/",
    "/chat",
    "/templates",
    "/automations",
    "/content",
    "/autopost",
    "/image",
    "/carousel-shots",
    "/video",
    "/assets",
    "/ai-influencer",
    "/canvases",
    "/canvas",
    "/dashboard",
    "/pricing",
    "/mcp",
  ],
  defaultSignedInRoute: "/dashboard",
  assistantName: "Presence Agent",
  onboardingEnabled: false,
  billingProvider: "fanvue",
  pageOverrides: {
    landing: "presence",
    dashboard: "default",
    pricing: "default",
  },
}
