import type { ProductConfig } from "@/lib/product/types"

export const presenceStudioProduct: ProductConfig = {
  id: "presence-studio",
  name: "Presence Studio",
  siteUrl: "https://artificialinfluence.tech",
  logo: "/presence_studio_logo.png",
  logoSizePx: 36,
  logoClassName: "relative z-10",
  favicon: "/presence-studio/favicon.ico",
  appleTouchIcon: "/presence-studio/apple-touch-icon.png",
  webManifest: "/presence-studio/site.webmanifest",
  themeClass: "theme-presence",
  metadata: {
    title: "Presence Studio - AI influencer content studio",
    titleTemplate: "%s | Presence Studio",
    description:
      "Create AI influencers, generate character-led content, reuse creator templates, and build a repeatable posting pipeline from one focused studio.",
  },
  landing: {
    heroTitle: "Create and grow AI influencers",
    heroDescription:
      "Build consistent characters, generate influencer content, reuse proven templates, and prepare posts from one focused AI creator studio.",
    primaryCtaLabel: "Start for free",
    primaryCtaHref: "/login?mode=signup",
    secondaryCtaLabel: "Explore templates",
    secondaryCtaHref: "/templates",
    previewAlt: "Presence Studio AI influencer workflow screenshot",
  },
  visibleRoutes: [
    "/",
    "/chat",
    "/templates",
    "/automations",
    "/content",
    "/autopost",
    "/image",
    "/carousel-shots",
    "/video",
    "/assets",
    "/ai-influencer",
    "/canvases",
    "/canvas",
    "/dashboard",
    "/pricing",
    "/mcp",
  ],
  defaultSignedInRoute: "/dashboard",
  assistantName: "Presence Agent",
  onboardingEnabled: false,
  billingProvider: "fanvue",
  pageOverrides: {
    landing: "presence",
    dashboard: "default",
    pricing: "default",
  },
}
