import type { ProductConfig } from "@/lib/product/types"

export const unicanProduct: ProductConfig = {
  id: "unican",
  name: "UniCan",
  siteUrl: "https://unican.ai",
  mcpSiteUrl: "https://mcp.unican.ai",
  logo: "/logo.svg",
  logoSizePx: 28,
  favicon: "/favicon.ico",
  themeClass: "theme-unican",
  metadata: {
    title: "UniCan - Automate faceless content and Instagram marketing with AI",
    titleTemplate: "%s | UniCan",
    description:
      "Create more content in less time with easy-to-use AI agents trained for high-quality image, video, and audio generation, plus TikTok and Instagram autoposting to put growth on autopilot.",
  },
  landing: {
    heroTitle: "Introducing vibe marketing",
    heroDescription:
      "Like Cursor, but for marketing. Create AI UGC, AI influencer content, brainrot, CGI-style campaigns, and static ads with natural language, and even schedule posts to Instagram automatically.",
    primaryCtaLabel: "Start free",
    primaryCtaHref: "/login?mode=signup",
    secondaryCtaLabel: "View pricing",
    secondaryCtaHref: "/#pricing",
    previewAlt: "UniCan agent screenshot",
  },
  visibleRoutes: [
    "/",
    "/chat",
    "/templates",
    "/slideshows",
    "/automations",
    "/autopost",
    "/image",
    "/video",
    "/audio",
    "/assets",
    "/brand",
    "/motion-copy",
    "/lipsync",
    "/inpaint",
    "/character-swap",
    "/ai-influencer",
    "/canvases",
    "/canvas",
    "/editor",
    "/resources",
    "/free-tools",
    "/pricing",
    "/mcp",
    "/dashboard",
    "/onboarding",
    "/upscale",
  ],
  defaultSignedInRoute: "/dashboard",
  assistantName: "UNI AGENT",
  onboardingEnabled: true,
}
