import type { TextItem } from "./types"

export type TextStylePreset = {
  id: string
  label: string
  description: string
  patch: Partial<TextItem>
  previewText?: string
}

const sansStack = '"TikTok Sans", "Montserrat", "Inter", system-ui, sans-serif'
const typewriterStack = '"Source Code Pro", "SFMono-Regular", Consolas, monospace'
const handwritingStack = '"Yesteryear", "Segoe Script", "Comic Sans MS", cursive'
const neonStack = '"Abel", "Arial Narrow", "Inter", system-ui, sans-serif'
const serifStack = 'Georgia, "Times New Roman", serif'

export const TIKTOK_TEXT_COLORS = [
  "#ffffff",
  "#000000",
  "#fee08b",
  "#f2cd46",
  "#ff933d",
  "#77c8d8",
  "#8ea5ff",
  "#9b7dff",
  "#f7a7c9",
  "#ff514f",
] as const

export const TEXT_STYLE_PRESETS: readonly TextStylePreset[] = [
  {
    id: "tiktok-original",
    label: "Original",
    description: "Simple TikTok default text: white fill, full black stroke, no background.",
    previewText: "Text",
    patch: {
      stylePresetId: "tiktok-original",
      fontFamily: '"TikTok Sans", "Montserrat", "Inter", system-ui, sans-serif',
      fontWeight: "800",
      fontStyle: "normal",
      fontSize: 72,
      textAlign: "center",
      lineHeight: 1,
      letterSpacingPx: 0,
      color: "#ffffff",
      backgroundColor: null,
      backgroundMode: "none",
      backgroundPaddingX: 0,
      backgroundPaddingY: 0,
      backgroundRadius: 0,
      textStrokeColor: "#000000",
      textStrokeWidth: 6,
      textShadow: "0 2px 0 rgba(0,0,0,0.95), 0 5px 14px rgba(0,0,0,0.45)",
      textTransform: "none",
    },
  },
  {
    id: "tiktok-classic",
    label: "TikTok Classic",
    description: "Semibold white rounded caption blocks, matching native TikTok overlay text.",
    previewText: "most people think",
    patch: {
      stylePresetId: "tiktok-classic",
      fontFamily: sansStack,
      fontWeight: "700",
      fontStyle: "normal",
      fontSize: 56,
      textAlign: "center",
      lineHeight: 1.12,
      letterSpacingPx: 0,
      color: "#111111",
      backgroundColor: "#ffffff",
      backgroundMode: "line",
      backgroundPaddingX: 14,
      backgroundPaddingY: 5,
      backgroundRadius: 7,
      textStrokeColor: "#000000",
      textStrokeWidth: 0,
      textShadow: "0 1px 1px rgba(0,0,0,0.18)",
      textTransform: "none",
    },
  },
  {
    id: "tiktok-creator-caption",
    label: "TikTok Creator",
    description: "Bold TikTok-native caption text with a heavy black outline for busy footage.",
    previewText: "YOU NEED THIS",
    patch: {
      stylePresetId: "tiktok-creator-caption",
      fontFamily: '"TikTok Sans", "Montserrat", "Arial Black", "Inter", system-ui, sans-serif',
      fontWeight: "900",
      fontStyle: "normal",
      fontSize: 76,
      textAlign: "center",
      lineHeight: 0.96,
      letterSpacingPx: 0,
      color: "#ffffff",
      backgroundColor: null,
      backgroundMode: "none",
      backgroundPaddingX: 0,
      backgroundPaddingY: 0,
      backgroundRadius: 0,
      textStrokeColor: "#000000",
      textStrokeWidth: 8,
      textShadow: "0 3px 0 rgba(0,0,0,0.98), 0 7px 18px rgba(0,0,0,0.5)",
      textTransform: "uppercase",
    },
  },
  {
    id: "tiktok-typewriter",
    label: "TikTok Typewriter",
    description: "Bold monospaced text with generous tracking and a solid editor-style block.",
    previewText: "story time",
    patch: {
      stylePresetId: "tiktok-typewriter",
      fontFamily: typewriterStack,
      fontWeight: "700",
      fontStyle: "normal",
      fontSize: 48,
      textAlign: "center",
      lineHeight: 1.2,
      letterSpacingPx: 2,
      color: "#ffffff",
      backgroundColor: "#000000",
      backgroundMode: "line",
      backgroundPaddingX: 12,
      backgroundPaddingY: 6,
      backgroundRadius: 2,
      textStrokeColor: "#000000",
      textStrokeWidth: 0,
      textShadow: "none",
      textTransform: "none",
    },
  },
  {
    id: "tiktok-neon",
    label: "TikTok Neon",
    description: "All-caps white letters with saturated cyan glow like TikTok neon text.",
    previewText: "NEON",
    patch: {
      stylePresetId: "tiktok-neon",
      fontFamily: neonStack,
      fontWeight: "700",
      fontStyle: "normal",
      fontSize: 70,
      textAlign: "center",
      lineHeight: 1,
      letterSpacingPx: 2,
      color: "#ffffff",
      backgroundColor: null,
      backgroundMode: "none",
      backgroundPaddingX: 0,
      backgroundPaddingY: 0,
      backgroundRadius: 0,
      textStrokeColor: "#33f6ff",
      textStrokeWidth: 1,
      textShadow: "0 0 5px #33f6ff, 0 0 16px #11cfff, 0 0 34px rgba(17,207,255,0.9)",
      textTransform: "uppercase",
    },
  },
  {
    id: "tiktok-serif",
    label: "TikTok Serif",
    description: "Bold Georgia-style serif for quote edits and clean aesthetic overlays.",
    previewText: "book quote",
    patch: {
      stylePresetId: "tiktok-serif",
      fontFamily: serifStack,
      fontWeight: "700",
      fontStyle: "normal",
      fontSize: 62,
      textAlign: "center",
      lineHeight: 1.08,
      letterSpacingPx: 0,
      color: "#ffffff",
      backgroundColor: null,
      backgroundMode: "none",
      backgroundPaddingX: 0,
      backgroundPaddingY: 0,
      backgroundRadius: 0,
      textStrokeColor: "#000000",
      textStrokeWidth: 2,
      textShadow: "0 3px 10px rgba(0,0,0,0.6)",
      textTransform: "none",
    },
  },
  {
    id: "tiktok-handwriting",
    label: "TikTok Handwriting",
    description: "Large cursive title text with a soft shadow for handwritten TikTok moments.",
    previewText: "little note",
    patch: {
      stylePresetId: "tiktok-handwriting",
      fontFamily: handwritingStack,
      fontWeight: "400",
      fontStyle: "normal",
      fontSize: 76,
      textAlign: "center",
      lineHeight: 1.05,
      letterSpacingPx: 0,
      color: "#ffffff",
      backgroundColor: null,
      backgroundMode: "none",
      backgroundPaddingX: 0,
      backgroundPaddingY: 0,
      backgroundRadius: 0,
      textStrokeColor: "#000000",
      textStrokeWidth: 1,
      textShadow: "0 3px 12px rgba(0,0,0,0.65)",
      textTransform: "none",
    },
  },
  {
    id: "snapchat-classic",
    label: "Snapchat Bar",
    description: "Classic Snapchat caption: white text on a media-width translucent black rounded bar.",
    previewText: "what are you looking at",
    patch: {
      stylePresetId: "snapchat-classic",
      fontFamily:
        '"Helvetica Neue", Helvetica, -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif',
      fontWeight: "700",
      fontStyle: "normal",
      fontSize: 46,
      textAlign: "center",
      lineHeight: 1.15,
      letterSpacingPx: 0,
      color: "#ffffff",
      backgroundColor: "rgba(0,0,0,0.75)",
      backgroundMode: "box",
      backgroundPaddingX: 18,
      backgroundPaddingY: 10,
      backgroundRadius: 8,
      textStrokeColor: "#000000",
      textStrokeWidth: 0,
      textShadow: "0 1px 1px rgba(0,0,0,0.35)",
      textTransform: "none",
    },
  },
]

export function findTextStylePreset(id: string | null | undefined): TextStylePreset | undefined {
  if (!id) return undefined
  return TEXT_STYLE_PRESETS.find((preset) => preset.id === id)
}
